### ISSUE TITLE
run predict.py error

### ISSUE THREAD

**Issue by yl0911** [chibohe/text_recognition_toolbox#11]
model_infor networks.DAN,DAN
当前处理的图片是: 2.jpg
Traceback (most recent call last):
  File "predict.py", line 110, in <module>
    preds_str = text_recognizer(image)
  File "predict.py", line 87, in __call__
    preds_str = self.predict(image_tensor)
  File "predict.py", line 79, in predict
    outputs = self.model(image_tensor)
  File "/ntt/Anaconda3/envs/ocr-py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/ntt/Anaconda3/envs/ocr-py38/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/ntt/Anaconda3/envs/ocr-py38/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/ntt/Anaconda3/envs/ocr-py38/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/ntt/Anaconda3/envs/ocr-py38/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/ntt/Anaconda3/envs/ocr-py38/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/ntt/Anaconda3/envs/ocr-py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'text'

**Comment by yl0911** [comment]
Hello, author, thank you for sharing
I saw your explanation in the other question section
This error seems to only occur on DAN, I tried CRNN, no such error
I still have two questions:
Whether single GPU training can only be GPU0
I tried this:
_Gpu_num: '3', device: Cuda :3
And gpu_num: '3', device: cuda:0_
Can't "train"
Can only be:
_Gpu_num: '0', device: Cuda :0
Gpu_num: '3,4', device: Cuda :0_

Also, importing the pre-training model during training will report an error
RuntimeError: Error(s) in loading state_dict for CRNN:
But the inference is not wrong

**Comment by chibohe** [comment]
I haven't implemented the inference part for DAN, please try CRNN, FAN, or SAR model.

**Comment by chibohe** [comment]
> Hello, author, thank you for sharing
> I saw your explanation in the other question section
> This error seems to only occur on DAN, I tried CRNN, no such error
> I still have two questions:
> Whether single GPU training can only be GPU0
> I tried this:
> _Gpu_num: '3', device: Cuda :3 And gpu_num: '3', device: cuda:0_
> Can't "train"
> Can only be:
> _Gpu_num: '0', device: Cuda :0 Gpu_num: '3,4', device: Cuda :0_
> 
> Also, importing the pre-training model during training will report an error
> RuntimeError: Error(s) in loading state_dict for CRNN:
> But the inference is not wrong

The predict script for DAN has been implemented, please try again.
